url: https://hausemodelica.github.io/modelica-association
baseurl: ""

collections:
  events:
    output: true

defaults:
  - scope:
      path: ""
    values:
      layout: "home"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

sass:
  sass_dir: _sass
  style: compressed

permalink: none

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
