url: hausemodelica.github.io/first-template

collections:
  events:
    output: true

defaults:
  - scope:
      path: ""
    values:
      layout: "home"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

