- icon: /assets/images/modelica_lang.svg
  title: Education
  info: Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
  link: #
- icon: /assets/images/modelica_lang.svg
  title: Training
  info: Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
  link: #
- icon: /assets/images/modelica_lang.svg
  title: Consulting
  info: Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
  link: #
- icon: /assets/images/modelica_lang.svg
  title: Downloads
  info: Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
  link: #
